name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  container:
    needs: check
    if: always()
    uses: ./.github/workflows/_container.yml
    with:
      publish: ${{ needs.check.result == 'success' }}
    permissions:
      contents: read
      packages: write

  helm:
    needs: check
    if: always()
    uses: ./.github/workflows/_helm.yml
    with:
      publish: ${{ needs.check.result == 'success' }}
    permissions:
      contents: read
      packages: write

  docs:
    uses: ./.github/workflows/_docs.yml
    permissions:
      contents: write

  release:
    needs: [check, container, helm]
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
